/*
  Copyright (c) 2014 Auston Sterling
  See LICENSE for copying permissions.
  
  -----Instruments Listing-----
  Auston Sterling
  austonst@gmail.com

  Contains constants to be used to easily set MIDI instruments.
  Uses General MIDI Level 1 Instrument Patches.
*/

#ifndef _instruments_hpp_
#define _instruments_hpp_

#include <cstdint>

namespace midi
{

  enum class Instrument : std::uint8_t
  {
    ACOUSTIC_GRAND_PIANO,
      BRIGHT_ACOUSTIC_PIANO,
      ELECTRIC_GRAND_PIANO,
      HONKY_TONK_PIANO,
      ELECTRIC_PIANO_1,
      ELECTRIC_PIANO_2,
      HARPSICHORD,
      CLAVI,
      CELESTA,
      GLOCKENSPIEL,
      MUSIC_BOX,
      VIBRAPHONE,
      MARIMBA,
      XYLOPHONE,
      TUBULAR_BELLS,
      DULCIMER,
      DRAWBAR_ORGAN,
      PERCUSSIVE_ORGAN,
      ROCK_ORGAN,
      CHURCH_ORGAN,
      REED_ORGAN,
      ACCORDION,
      HARMONICA,
      TANGO_ACCORDION,
      ACOUSTIC_GUITAR_NYLON,
      ACOUSTIC_GUITAR_STEEL,
      ELECTRIC_GUITAR_JAZZ,
      ELECTRIC_GUITAR_CLEAN,
      ELECTRIC_GUITAR_MUTED,
      OVERDRIVEN_GUITAR,
      DISTORTION_GUITAR,
      GUITAR_HARMONICS,
      ACOUSTIC_BASS,
      ELECTRIC_BASS_FINGER,
      ELECTRIC_BASS_PICK,
      FRETLESS_BASS,
      SLAP_BASS_1,
      SLAP_BASS_2,
      SYNTH_BASS_1,
      SYNTH_BASS_2,
      VIOLIN,
      VIOLA,
      CELLO,
      CONTRABASS,
      TREMOLO_STRINGS,
      PIZZICATO_STRINGS,
      ORCHESTRAL_HARP,
      TIMPANI,
      STRING_ENSEMBLE_1,
      STRING_ENSEMBLE_2,
      SYNTHSTRINGS_1,
      SYNTHSTRINGS_2,
      CHOIR_AAHS,
      CHOIR_OOHS,
      SYNTH_VOICE,
      ORCHESTRA_HIT,
      TRUMPET,
      TROMBONE,
      TUBA,
      MUTED_TRUMPET,
      FRENCH_HORN,
      BRASS_SECTION,
      SYNTHBRASS_1,
      SYNTHBRASS_2,
      SOPRANO_SAX,
      ALTO_SAX,
      TENOR_SAX,
      BARITONE_SAX,
      OBOE,
      ENGLISH_HORN,
      BASSOON,
      CLARINET,
      PICCOLO,
      FLUTE,
      RECORDER,
      PAN_FLUTE,
      BLOWN_BOTTLE,
      SHAKUHACHI,
      WHISTLE,
      OCARINA,
      LEAD_1,
      LEAD_SQUARE,
      LEAD_2,
      LEAD_SAWTOOTH,
      LEAD_3,
      LEAD_CALLIOPE,
      LEAD_4,
      LEAD_CHIFF,
      LEAD_5,
      LEAD_CHARANG,
      LEAD_6,
      LEAD_VOICE,
      LEAD_7,
      LEAD_FIFTHS,
      LEAD_8,
      LEAD_BASS_LEAD,
      PAD_1,
      PAD_NEW_AGE,
      PAD_2,
      PAD_WARM,
      PAD_3,
      PAD_POLYSYNTH,
      PAD_4,
      PAD_CHOIR,
      PAD_5,
      PAD_BOWED,
      PAD_6,
      PAD_METALLIC,
      PAD_7,
      PAD_HALO,
      PAD_8,
      PAD_SWEEP,
      FX_1,
      FX_RAIN,
      FX_2,
      FX_SOUNDTRACK,
      FX_3,
      FX_CRYSTAL,
      FX_4,
      FX_ATMOSPHERE,
      FX_5,
      FX_BRIGHTNESS,
      FX_6,
      FX_GOBLINS,
      FX_7,
      FX_ECHOES,
      FX_8,
      FX_SCI_FI,
      SITAR,
      BANJO,
      SHAMISEN,
      KOTO,
      KALIMBA,
      BAG_PIPE,
      FIDDLE,
      SHANAI,
      TINKLE_BELL,
      AGOGO,
      STEEL_DRUMS,
      WOODBLOCK,
      TAIKO_DRUM,
      MELODIC_TOM,
      SYNTH_DRUM,
      REVERSE_CYMBAL,
      GUITAR_FRET_NOISE,
      BREATH_NOISE,
      SEASHORE,
      BIRD_TWEET,
      TELEPHONE_RING,
      HELICOPTER,
      APPLAUSE,
      GUNSHOT
      };
  
} //Namespace

#endif
